version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my-net
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

  server:
    container_name: server
    image: 'node:12'
    working_dir: /app
    restart: on-failure
    ports:
      - '9000:9000'
    depends_on:
      - rabbitmq
    networks:
      - my-net
    volumes:
      - ./server:/app
      - /app/node_modules
    command: 'sh -c "yarn && yarn start:dev"'

  client:
    container_name: client
    build:
      context: ./client
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - my-net
    volumes:
      - ./client:/app
      - /app/node_modules
    command: 'sh -c "yarn && yarn start"'


networks:
  my-net:
    driver: bridge
