version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my-net
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

  api-service:
    container_name: api-service
    image: 'node:12'
    working_dir: /app
    ports:
      - '50000:50000'
    networks:
      - my-net
    volumes:
      - .:/app
      - /app/node_modules
    command: 'sh -c "yarn && yarn start:dev"'

networks:
  my-net:
    driver: bridge

